In [1]:
# ブールインデックス参照

"""
ブールの役割を利用して、データを取り出す。
配列の参照に、配列と同じサイズのブール値配列を渡すことで、
Trueのインデックスの値のみを取り出すことができる。
"""
import numpy as np

names = np.array(['a', 'b', 'c', 'd', 'a'])
data = np.random.randn(5, 5)

t = names == 'a' # [True,False,False,False,True]

print(data)
print(data[t]) # 0番目と4番目の値が出力される

[[-0.12493383 -0.11731664 -0.9205801   0.30915741  1.05113253]
 [-0.54575397  0.48990821  0.65545439  0.40194981  0.05469872]
 [-0.93738544  0.42203839  0.15978852  1.26399152 -0.23779847]
 [-0.27828554 -1.19079286 -0.12298422  0.98575431 -0.80810093]
 [ 0.65807115 -0.06588705  0.07801641 -0.0833836  -0.36203156]]
[[-0.12493383 -0.11731664 -0.9205801   0.30915741  1.05113253]
 [ 0.65807115 -0.06588705  0.07801641 -0.0833836  -0.36203156]]


In [2]:
# ユニバーサル関数
import numpy as np

sample_data = np.arange(10)
print(np.sqrt(sample_data))
print(np.exp(sample_data))

[ 0.          1.          1.41421356  1.73205081  2.          2.23606798
  2.44948974  2.64575131  2.82842712  3.        ]
[  1.00000000e+00   2.71828183e+00   7.38905610e+00   2.00855369e+01
   5.45981500e+01   1.48413159e+02   4.03428793e+02   1.09663316e+03
   2.98095799e+03   8.10308393e+03]


In [4]:
import numpy as np

sample_multi_array_data1 = np.arange(9).reshape(3, 3)
print(sample_multi_array_data1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [5]:
print('平均', sample_multi_array_data1.mean())

平均 4.0


In [6]:
print('最大', sample_multi_array_data1.max())

最大 8


In [7]:
print('最小', sample_multi_array_data1.min())

最小 0


In [8]:
print('合計', sample_multi_array_data1.sum())

合計 36


In [10]:
print('行の合計', sample_multi_array_data1.sum(axis=1))

行の合計 [ 3 12 21]


In [11]:
print('列の合計', sample_multi_array_data1.sum(axis=0))

列の合計 [ 9 12 15]


In [12]:
# 多次元配列の計算
"""
多次元配列とは、数字の集合であり、数字をN次元状に並べたもの
"""
import numpy as np
n1 = np.array([1, 2, 3, 4, 5])
print(n1)

[1 2 3 4 5]


In [14]:
# 配列の次元数をnp.ndim()で取得
np.ndim(n1)

1

In [16]:
# 配列の形状取得
n1.shape

(5,)

In [17]:
n2 = np.array([[1, 2], [3, 4], [5, 6]])
print(n2)

[[1 2]
 [3 4]
 [5 6]]


In [18]:
np.ndim(n2)

2

In [19]:
# 3*2の配列
# 最初の次元に３つの要素があり、次の次元に２つの要素がある
n2.shape

(3, 2)

In [20]:
# アレイを作る
"""
Pythonのリストを元にアレイを作る
"""
import numpy as np

my_list1 = [1, 2, 3, 4, 5]
my_array1 = np.array(my_list1)
print(my_array1)

[1 2 3 4 5]


In [21]:
my_list2 = [10, 20, 30, 40, 50]
my_array2 = np.array(my_list2)
print(my_array2)

[10 20 30 40 50]


In [23]:
my_lists = [my_list1, my_list2]
print(my_lists)

[[1, 2, 3, 4, 5], [10, 20, 30, 40, 50]]


In [24]:
my_lists2 = np.array(my_lists)
print(my_lists2)

[[ 1  2  3  4  5]
 [10 20 30 40 50]]
