In [1]:
# 2次元配列
"""
np.array([リスト, リスト)
- ndarray変数.shape()
    - 各次元ごとの各要素を返すことができる
- ndarray変数.reshape(a,b)
    - 指定した引数と同じ形の行列を作る
"""
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [2]:
print(arr.shape)

(2, 4)


In [3]:
print(arr.reshape(4, 2))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [4]:
# インデックス参照とスライス
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [5]:
print(arr[1])

[5 6 7 8]


In [6]:
print(arr[0][1])

2


In [7]:
print(arr[0][0:])

[1 2 3 4]


In [8]:
print(arr[0][0:2])

[1 2]


In [9]:
print(arr[0, 2])

3


In [10]:
print(arr[0][1:3], arr[1][1:3])

[2 3] [6 7]


In [15]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
# 3を抽出
print(arr[0, 2])

3


In [17]:
print(arr[1:, :2])

[[4 5]
 [7 8]]


In [19]:
print(arr.reshape(9, 1))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
