In [1]:
# viewとcopy
"""
ndarrayのスライスは配列のコピーではなくview
viewとは元の配列と同じデータを指している
スライスをコピーとして扱いたい場合、arr[:].copy()とする
"""
import numpy as np

# Pythonのリストのスライス
arr_list = [x for x in range(10)]
print(arr_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [3]:
arr_list_copy = arr_list[:]
print(arr_list_copy)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [4]:
arr_list_copy[0] = 100
print(arr_list_copy)

[100, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [5]:
# リストのスライスではコピーが作られるので、arr_list_copyの変更は反映されない
print(arr_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [6]:
# ndarrayのスライス
arr_numpy = np.arange(10)
print(arr_numpy)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
arr_numpy_view = arr_numpy[:]
print(arr_numpy_view)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
arr_numpy_view[0] = 100
print(arr_numpy_view)

[100   1   2   3   4   5   6   7   8   9]


In [9]:
# arr_numpyの値も変更される
print(arr_numpy)

[100   1   2   3   4   5   6   7   8   9]


In [11]:
arr_Numpy = np.arange(10)
print(arr_Numpy)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
arr_Numpy_copy = arr_Numpy[:].copy()
print(arr_Numpy_copy)

[0 1 2 3 4 5 6 7 8 9]


In [13]:
arr_Numpy_copy[0] = 100
print(arr_Numpy_copy)

[100   1   2   3   4   5   6   7   8   9]


In [14]:
# .copy()を使うとarr_Numpyの値は変更されない
print(arr_Numpy)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
# ブールインデックス参照
"""
[]の中に論理値の配列を用いて要素を取り出すこと
arr[ndarrayの論理値の配列]と表記すると、
論理値配列のTrueに該当する要素のndarrayを作成して返す
"""
import numpy as np

arr = np.array([2, 4, 6, 7])
print(arr[np.array([True, True, True, False])])

[2 4 6]


In [19]:
print(arr[arr % 3 == 1])

[4 7]


In [20]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
print(arr[arr % 2 == 0])

[2 4 6]


In [21]:
print(arr % 2 == 0)

[False  True False  True False  True]


In [22]:
# ユニバーサル関数
"""
ndaaray配列の各要素に対して演算した結果を返す関数
- 多次元配列でも使用可能
- 引数が一つのものと二つのものがある
    - 一つのもの
        - np.abs()
            - 要素の絶対値を返す
        - np.exp()
            - 要素のe(自然対数の底)のべき乗を返す
        - np.sqrt()
            - 平方根を返す
    - 二つのもの
        - np.add()
            - 要素同士の和を返す
        - np.subtract()
            - 要素同士の差を返す
        - np.maximum()
            - 要素同士の最大値を格納した配列を返す
"""
import numpy as np

arr = np.array([4, 9, -4, 16, 20])
print(arr)

[ 4  9 -4 16 20]


In [23]:
# 絶対値
arr_abs = np.abs(arr)
print(arr_abs)

[ 4  9  4 16 20]


In [24]:
# eのべき乗
print(np.exp(arr_abs))

[  5.45981500e+01   8.10308393e+03   5.45981500e+01   8.88611052e+06
   4.85165195e+08]


In [25]:
# 平方根
print(np.sqrt(arr_abs))

[ 2.          3.          2.          4.          4.47213595]


In [26]:
# 集合関数
"""
数学の集合演算を行う関数
一次元配列のみ対象
- np.unique()
    - 重複を取り除き、ソートした結果を返す
- np.union1d(x, y)
    - 配列x, yのうち、少なくとも一方に存在する取り出しソートする(和集合)
- np.intersect1d(x, y)
    - 配列x, yのうち共通する要素を取り出しソートする(積集合)
-np.setdiff1d(x, y)
    - 配列xから配列yに存在する要素を取り除きソートする
"""
import numpy as np

arr1 = [2, 5, 7, 9, 5, 2]
arr2 = [2, 5, 8, 3, 1]

# 重複を取り除く
new_arr1 = np.unique(arr1)
print(new_arr1)

[2 5 7 9]


In [27]:
# 和集合
print(np.union1d(arr1, arr2))

[1 2 3 5 7 8 9]


In [28]:
# 積集合
print(np.intersect1d(arr1, arr2))

[2 5]


In [29]:
# 差集合
print(np.setdiff1d(arr1, arr2))

[7 9]


In [32]:
# 乱数
"""
np.randomモジュールで乱数を生成することができる
- np.random.rand()
    - 0以上1未満の一様乱数を生成する
    - ()の中に整数を入れることで、整数分の乱数を生成できる
- np.random.randint(x, y, z)
    - x以上y未満の乱数をz個生成
- np.random.normal()
    - 関数やガウス分布に従う乱数を生成
from numpy.random import randintをしておくとrandint()のみで使用できる
from モジュール名 import モジュール内にある関数名  
"""
import numpy as np
from numpy.random import randint

arr1 = randint(0, 10, (5, 2))
print(arr1)

[[7 9]
 [0 9]
 [3 2]
 [5 3]
 [6 4]]


In [33]:
arr2 = np.random.rand(3)
print(arr2)

[ 0.78644351  0.77354336  0.67946584]
