In [1]:
# axis
"""
axisは座標軸のようなもの
- 列ごとに処理を行う軸axis=0
- 行ごとに処理を行う軸axis=1
- ndarray.sum()
    - 要素を足し合わせる
"""
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [2]:
# すべての要素を足す
print(arr.sum())

21


In [3]:
# axis=0
# 列ごとの処理
print(arr.sum(axis=0))

[5 7 9]


In [4]:
# axis=1
# 行ごとの処理
print(arr.sum(axis=1))

[ 6 15]


In [10]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
print(arr.sum(axis=1))

[ 6 15 24]


In [12]:
# ファンシーインデックス参照
"""
インデックス参照にインデックスの配列を用いる
スライスとは異なり、常に元データのコピーを返す
"""
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [13]:
# ３行目、２行目、０行目の順に出力
print(arr[[3, 2, 0]])

[[7 8]
 [5 6]
 [1 2]]


In [14]:
import numpy as np

arr = np.arange(25).reshape(5, 5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [ ]:
print(arr[[1, 3, 0]])