In [1]:
# 行列計算
"""
np.dot()
- 二つの行列の行列積を返す
- 行列積とは、行列の中にある行ベクトルと列ベクトルとの内積を要素とする行列が新たに作り出されること
np.linalg.norm()
- 関数やノルムを返す
- ベクトルの長さを返すもの
- 要素の二乗値を掛け合わせて、ルートを被せたもの
"""
import numpy as np

arr = np.arange(9).reshape(3, 3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [3]:
# 行列積
print(np.dot(arr, arr))

[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]


In [ ]:
# ノルム
print(np.)